[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.package]
version = "0.0.3"
edition = "2021"
rust-version = "1.83"
description = "cdk-ansible is a tool to generate Ansible playbooks from Rust code."
homepage = "https://github.com/pollenjp/cdk-ansible"
documentation = "https://github.com/pollenjp/cdk-ansible"
repository = "https://github.com/pollenjp/cdk-ansible"
authors = ["pollenjp"]
license = "MIT"

[workspace.dependencies]
cdk-ansible = { path = "crates/cdk-ansible" }
# should be the same as the version of 'cdk-ansible' crate
cdk-ansible-cli = { version = "0.0.3", path = "crates/cdk-ansible-cli" }
cdk-ansible-core = { version = "0.0.2", path = "crates/cdk-ansible-core" }
cdk-ansible-static = { version = "0.0.1", path = "crates/cdk-ansible-static" }
cdk-ansible-macro = { version = "0.0.2", path = "crates/cdk-ansible-macro" }

anyhow = { version = "1.0.95" }
cargo-util-schemas = { version = "0.7.1" }
clap = { version = "4.5.21", features = [
    "derive",
    "env",
    "string",
    "wrap_help",
] }
dyn-clone = "1.0.17"
erased-serde = "0.4.5"
fs-err = "3.0.0"
indexmap = { version = "2.7.1", features = ["serde"] }
quote = "1.0.37"
semver = "1.0.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
syn = { version = "2.0.90", features = ["full"] }
toml = "0.8.19"

[workspace.lints.rust]

[workspace.lints.clippy]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
