# https://release-plz.dev/docs/config
[workspace]
release = false
changelog_update = true
publish = false

# Only 'cdk-ansible-cli' is released and it is released through 'dist'
git_release_enable = false

git_tag_enable = true

[[package]]
name = "cdk-ansible"
release = true

[[package]]
name = "cdk-ansible-cli"
release = true

[[package]]
name = "cdk-ansible-core"
release = true

[[package]]
name = "cdk-ansible-static"
release = true

[[package]]
name = "cdk-ansible-macro"
release = true

[changelog]
# cdk-ansible-cli is released via dist (cargo-dist)
# When releasing with dist, the announcement information references the changelog
# release name in Cargo.toml's `package.metadata.binstall.pkg-url` and `announcement_title` need to match
#
# https://github.com/axodotdev/cargo-dist/blob/5ded22494ed88797a7b6ca48228a982a9f842671/axoproject/src/changelog.rs#L81-L93
# https://release-plz.dev/docs/changelog/format
body = """
## {{ package }}-v{{ version }}

[{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""
