# https://release-plz.dev/docs/config
[workspace]
release = false
changelog_update = true
publish = false

# Only 'cdk-ansible-cli' is released and it is released through 'dist'
git_release_enable = false

git_tag_enable = true

[[package]]
name = "cdk-ansible"
release = true
publish = true

[[package]]
name = "cdk-ansible-cli"
release = true
publish = true

[[package]]
name = "cdk-ansible-core"
release = true
publish = true

[[package]]
name = "cdk-ansible-static"
release = true
publish = true

[[package]]
name = "cdk-ansible-macro"
release = true
publish = true

[changelog]
# default body: https://github.com/release-plz/release-plz/blob/df66f3613195201c400931885f7fe7665fbce80c/crates/release_plz_core/src/changelog.rs#L414
body = """

## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }} ({{ package }})
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""
