[package]
name = "cdk-ansible-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cdk-ansible-static.workspace = true
cdk-ansible-version.workspace = true

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
