[package]
name = "cdk-ansible-cli"
# Use workspace value because 'version' function is defined in this crate
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/cdk-ansible-cli"
repository.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
cdk-ansible-static.workspace = true

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
