[package]
name = "cdk-ansible-cli"
# Use workspace value because 'version' function is defined in this crate
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/cdk-ansible-cli"
repository.workspace = true
authors.workspace = true
license.workspace = true

[lints.clippy]
all = "deny"
redundant_pub_crate = "warn"
# unreachable_pub = "warn"

[dependencies]
cdk-ansible-static.workspace = true
cdk-ansible-core.workspace = true
cdk-ansible-macro.workspace = true

anyhow.workspace = true
cargo_toml.workspace = true
clap.workspace = true
fs-err.workspace = true
indexmap.workspace = true
quote.workspace = true
regex.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
toml.workspace = true
