#!/usr/bin/env bash
set -euCx -o pipefail

proj_root=$(git rev-parse --show-toplevel)
ansible_uv=(uv --project "${proj_root}/tools/ansible")

random_str=$(dd if=/dev/urandom bs=1024 count=1 2>/dev/null | tr -dc A-Za-z0-9 | fold -w 10 | awk 'NR<=1')
date_str=$(date +%Y%m%d-%H%M%S)
temp_dir=~/.cdk-ansible-tmp/"${date_str}-${random_str}"
mkdir -p "${temp_dir}"

cleanup() {
  local exit_code=$?
  echo "cleanup..."
  rm -rf "${temp_dir}"
  exit "${exit_code}"
}

trap cleanup EXIT

# check help
pushd "${proj_root}"
"${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- --version
"${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- -V
"${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- help
"${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- init --version
"${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- init --help
popd

# pushd "${proj_root}"
# "${ansible_uv[@]}" run cargo run --package cdk-ansible-cli -- init --dir "${temp_dir}"
# popd

# # check build
# pushd "${temp_dir}"
# cargo build
# popd
