#!/usr/bin/env bash
#MISE description="Test simple sample 'l1'"
#MISE env={ RUST_BACKTRACE = "1" }
#MISE depends=["test:simple-sample-cli-module"]
#MISE depends_post=[]

set -euo pipefail -x

sample_ansible_root=$(realpath "${SAMPLE_ANSIBLE_ROOT:?}")

global_args=(
  --app-dir "${sample_ansible_root}"
)

stringify_cmd=(uv run python -c 'import sys; from shlex import join; print(join(sys.argv[1:]))')
playbook_command_str=$(
  "${stringify_cmd[@]}" \
    uv --project "${sample_ansible_root}" \
    run --directory "${sample_ansible_root}" \
    ansible-playbook -v
)
cargo run --package simple-sample --bin l1 -- "${global_args[@]}" deploy -P 3 --playbook-command "${playbook_command_str}" -i dev SampleStack
