#!/usr/bin/env bash
#MISE description="Test simple sample"
#MISE env.RUST_BACKTRACE=1
#MISE depends_post=["lint:ansible"]

set -euo pipefail

module_names=(
  'ansible\.builtin\.debug'
  'ansible\.builtin\.service_facts'
)
module_regex=$(
  IFS='|'
  echo "${module_names[*]}"
)

uv --project "${SAMPLE_ANSIBLE_ROOT:?}" run \
  cargo run --package cdk-ansible-cli -- \
  module --pkg-prefix 'sample_cdkam' --output-dir "${RS_OUT_DIR}" --module-name-regex "${module_regex}"

# Run 'synth' to generate playbooks and inventory
cargo run --package simple-sample -- synth --output-dir "${SAMPLE_ANSIBLE_ROOT}"

# shellcheck disable=SC2016
yq_script='yq -p json -o yaml "${1}" > "${1%.json}.yaml"'

# Convert json to yaml by yq
find "${SAMPLE_ANSIBLE_ROOT:?}/playbooks" "${SAMPLE_ANSIBLE_ROOT:?}/inventory" -name "*.json" -print0 \
  | xargs -P0 -0 -I{} bash -c "${yq_script}" _ {}
