#!/usr/bin/env bash
#MISE description="Test simple sample"
#MISE env={ RUST_BACKTRACE = "1" }
#MISE depends=["test:simple-sample-module"]
#MISE depends_post=["lint:simple-sample-ansible"]

set -euo pipefail -x

simple_sample_ansible_dir=./tools/ansible

global_args=(
  --app-dir "${simple_sample_ansible_dir}"
)

echo "================================================================================"
cargo run --package simple-sample -- "${global_args[@]}" help

echo "================================================================================"
cargo run --package simple-sample -- "${global_args[@]}" synth --help
cargo run --package simple-sample -- "${global_args[@]}" synth

# shellcheck disable=SC2016
yq_script='yq -p json -o yaml "${1}" > "${1%.json}.yaml"'

# Convert json to yaml by yq
find "${simple_sample_ansible_dir}/inventory" "${simple_sample_ansible_dir}/playbooks" -name "*.json" -print0 \
  | xargs -P0 -0 -I{} bash -ec "${yq_script}" _ {}

echo "================================================================================"
cargo run --package simple-sample -- "${global_args[@]}" deploy --help
# cargo run --package simple-sample -- deploy
