#!/usr/bin/env bash
#MISE description="Test simple sample 'l1'"
#MISE env={ RUST_BACKTRACE = "1" }
#MISE depends=["test:simple-sample-cli-module"]
#MISE depends_post=[]

set -euo pipefail -x

simple_sample_ansible_dir=./tools/ansible

global_args=(
  --app-dir "${simple_sample_ansible_dir}"
)

stringify_cmd=(uv run python -c 'import sys; from shlex import join; print(join(sys.argv[1:]))')
playbook_command_str=$(
  "${stringify_cmd[@]}" \
    uv --project "${simple_sample_ansible_dir}" \
    run --directory "${simple_sample_ansible_dir}" \
    ansible-playbook -v
)
cargo run --package simple-sample --bin simple-sample -- "${global_args[@]}" deploy -P 3 --playbook-command "${playbook_command_str}" -i dev SampleStack
