[package]
name = "cdk-ansible-macro"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
