[package]
name = "cdkam_ansible"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
anyhow = "1.0.95"
indexmap = "2.7.1"
serde = "1.0.217"
serde_json = "1.0.138"

[dependencies.cdk-ansible]
workspace = true
