name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash -eux -o pipefail {0}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint-rust
        working-directory: .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: make test
        working-directory: .
