name: Rust CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash -eux -o pipefail {0}
env:
  CI_JOB: 1
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2
        with:
          version: 2025.6.1
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
          working_directory: .
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - name: Lint
        run: mise run lint:rust
        working-directory: .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - name: Test
        run: cargo test --all-features --verbose
  mise-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2
        with:
          version: 2025.6.1
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
      - run: rustup component add rustfmt
      - run: mise run test
  mise-test-simple-sample-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2
        with:
          version: 2025.6.1
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
      - run: rustup component add rustfmt
      - run: mise run test:simple-sample-cli-module
      - name: Check dirty
        run: |
          status=$(git status --porcelain)
          if [ -z "$status" ]; then
              echo "No changes"
          else
              echo "Dirty"
              echo "$status"
              exit 1
          fi
  latest_deps: # https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-latest-dependencies
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo update --verbose
      - run: cargo build --verbose
      - run: cargo test --all-features --verbose
